### ISSUE TITLE
Deadtime module misbehavior

### ISSUE THREAD

**Issue by physicboy** [aesim-tech/simba-project#310]
Simulation file is sent via email to manu.

The issue occurs when fixed step solver is used

![image](https://github.com/aesim-tech/simba-project/assets/64262286/b429e792-0f31-408e-9918-4570a6edd76f)
![image](https://github.com/aesim-tech/simba-project/assets/64262286/d129969c-10b5-4b8e-9009-7bf223d96068)

**Comment by manu-aesim** [comment]
Hi Arief,

This one was interesting! The problem was due to the diode switching interpolation algorithm. The internal variables of the dead-time devices storing the next events were being interpolated, causing this odd behavior.

I simply disabled this interpolation algorithm for these variables and this seems to have solved the problem.

<img width="1728" alt="image" src="https://github.com/aesim-tech/simba-project/assets/112709259/dc6b57a7-8696-408f-b5ba-7b41718cd0a9">

You can try it out in this beta release:  https://aesimtech.s3.amazonaws.com/artifacts/Op5LCY2LH7D5etB87nASRPXSmuLnOh9C/simba.exe 

Let me know if this works. I will close the issue for now. 

Thanks,
Manu.
